// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914060651_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Models.GameConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BalanceBaseMaxBombs")
                        .HasColumnType("int");

                    b.Property<int>("BalanceBaseRange")
                        .HasColumnType("int");

                    b.Property<float>("BalanceBaseSpeed")
                        .HasColumnType("float");

                    b.Property<float>("BalanceBombRequestTimeoutSeconds")
                        .HasColumnType("float");

                    b.Property<float>("BalanceFuseSeconds")
                        .HasColumnType("float");

                    b.Property<int>("BalanceMatchDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("BalanceMaxBombs")
                        .HasColumnType("int");

                    b.Property<int>("BalanceMaxRange")
                        .HasColumnType("int");

                    b.Property<int>("BalanceMaxSpeedLevel")
                        .HasColumnType("int");

                    b.Property<float>("BalanceRemoteMaxSeconds")
                        .HasColumnType("float");

                    b.Property<int>("BalanceThrowDistanceCells")
                        .HasColumnType("int");

                    b.Property<float>("BalanceThrowDurationSeconds")
                        .HasColumnType("float");

                    b.Property<float>("BalanceTimedFuseSeconds")
                        .HasColumnType("float");

                    b.Property<float>("BalanceWallCooldownSeconds")
                        .HasColumnType("float");

                    b.Property<float>("BalanceWallDurationSeconds")
                        .HasColumnType("float");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("int");

                    b.Property<string>("EnabledMapIds")
                        .HasColumnType("longtext");

                    b.Property<string>("MinClientVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GameConfig");
                });

            modelBuilder.Entity("API.Models.Match", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EndReason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MatchId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("API.Models.MatchPlayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<bool>("Disconnected")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Placement")
                        .HasColumnType("int");

                    b.Property<int>("PowerUpsCollected")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("API.Models.PlayerSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("GraphicsQuality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("SfxVolume")
                        .HasColumnType("float");

                    b.Property<bool>("SoundEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("SwipeThresholdCm")
                        .HasColumnType("float");

                    b.Property<int>("TargetFps")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("PlayerSettings");
                });

            modelBuilder.Entity("API.Models.PlayerStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("PowerUpsCollected")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("API.Models.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SelectedSkinId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnlockedSkinIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("API.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("API.Models.Skin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EnabledInSelector")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skins");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Models.MatchPlayer", b =>
                {
                    b.HasOne("API.Models.Match", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("API.Models.PlayerSettings", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithOne("PlayerSettings")
                        .HasForeignKey("API.Models.PlayerSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.PlayerStats", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithOne("PlayerStats")
                        .HasForeignKey("API.Models.PlayerStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Profile", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("API.Models.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.RefreshToken", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Match", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Navigation("PlayerSettings");

                    b.Navigation("PlayerStats");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
