@APIBomberman_HostAddress = http://localhost:5201

GET {{APIBomberman_HostAddress}}/weatherforecast/
Accept: application/json

###

### Registrar usuario
POST https://localhost:7048/api/auth/register
Content-Type: application/json

{
  "name": "Marvin Raydel Rios Aguilar",
  "password": "admin"
}

### Login
# @name login
POST {{APIBomberman_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "name": "Marvin Raydel Rios Aguilar",
  "password": "admin"
}

### Obtener usuarios usando el token del login anterior
GET {{APIBomberman_HostAddress}}/api/users
Authorization: Bearer {{login.response.body.$.token}}
